### ISSUE TITLE
Is it empty？

### ISSUE THREAD

**Issue by retioa11** [wandahangFY/YOLO-MIF#1]
When do you upload the full version? Look forward to it, thank you.

**Comment by wandahangFY** [comment]
The code related to the paper is being organized into a standalone version, which will be open-sourced as an initial version after next Monday. The open-source code and operation process of other papers (such as MLCA and RIR) can already be found on my homepage. If needed, the code of this paper can be privately sent to your email in advance.

 Thank you for your attention, I hope to provide you with useful information and assistance. If you have any questions or needs, please feel free to contact me. I wish you a happy life!

万达航
***@***.***

签名由 网易灵犀办公 定制


Original:
From:retioa11< ***@***.***>Date:2024-03-22 11:53:43To:wandahangFY/YOLO-MIF< ***@***.***>Cc:Subscribed< ***@***.***>Subject:[wandahangFY/YOLO-MIF] Is it empty？ (Issue #1)
When do you upload the full version? Look forward to it, thank you.

**Comment by wandahangFY** [comment]
If all goes well, it should be released by next Monday (3.25) at the latest next Wednesday(3.27). We need to conduct tests on multiple computers in advance to eliminate hidden bugs in the first version. We apologize for any inconvenience this may cause. Thank you for your understanding.

万达航
***@***.***

签名由 网易灵犀办公 定制


Original:
From:retioa11< ***@***.***>Date:2024-03-22 11:53:43To:wandahangFY/YOLO-MIF< ***@***.***>Cc:Subscribed< ***@***.***>Subject:[wandahangFY/YOLO-MIF] Is it empty？ (Issue #1)
When do you upload the full version? Look forward to it, thank you.

**Comment by retioa11** [comment]
Ok，Thank you。

**Comment by wandahangFY** [comment]
The code has been uploaded; please contact us if you have any questions.
