### ISSUE TITLE
如何用自己的数据集train RGBT

### ISSUE THREAD

**Issue by xstjs** [wandahangFY/YOLO-MIF#3]
![3f3249ba58d6d02017ca71708ce21e9](https://github.com/user-attachments/assets/228ee85c-307d-4188-bebb-7ee7a3399569)
非常想要知道是否像这样组织架构?
如果如图1，关于dataset的yaml文件又要如何编写，这样可以吗
![image](https://github.com/user-attachments/assets/123d3095-8a4b-469e-9fbd-7f8f744f69c9)
![image](https://github.com/user-attachments/assets/c9dd8994-b83c-462a-b070-f1b58ba3116a)
如此组织架构，报错显示
![image](https://github.com/user-attachments/assets/54b8dd9a-51fa-49b0-89ed-494f0ed895ee)
labels架构需要与images完全一致对吗？

**Comment by xstjs** [comment]
![image](https://github.com/user-attachments/assets/7af8b0a6-c77d-4518-9e29-54ac7396b15e)
labels我直接 这样放了

**Comment by wandahangFY** [comment]
yaml文件和YOLOv5或者v8保持一致即可
 万达航
***@***.***
  签名由 网易灵犀办公 定制


Original:
From:xstjs< ***@***.***>Date:2024-08-20 20:17:40To:wandahangFY/YOLO-MIF< ***@***.***>Cc:Subscribed< ***@***.***>Subject:[wandahangFY/YOLO-MIF] 如何用自己的数据集train RGBT (Issue #3)
3f3249ba58d6d02017ca71708ce21e9.png (view on web)
 非常想要知道是否像这样组织架构?
 如果如图1，关于dataset的yaml文件又要如何编写，这样可以吗
 image.png (view on web)
 image.png (view on web)
 如此组织架构，报错显示
 image.png (view on web)
 labels架构需要与images完全一致对吗？

**Comment by wandahangFY** [comment]
1753205688
你加这个qq，我这会儿连不上github,看不到图
 万达航
***@***.***
  签名由 网易灵犀办公 定制


Original:
From:xstjs< ***@***.***>Date:2024-08-20 20:19:02To:wandahangFY/YOLO-MIF< ***@***.***>Cc:Subscribed< ***@***.***>Subject:Re: [wandahangFY/YOLO-MIF] 如何用自己的数据集train RGBT (Issue #3)
image.png (view on web)
 labels我直接 这样放了

**Comment by xstjs** [comment]
太感谢！
