### ISSUE TITLE
DeepDBB结构图与代码不对应？

### ISSUE THREAD

**Issue by bolt958** [wandahangFY/YOLO-MIF#7]
你好！你们的工作对我启发很大！
我在研究DeepDBB时，发现代码中所对应的第二条分支（后半段的K*K接BN）似乎并没有被替换为图中的LDBB，请问是我的理解错了吗，请指正，感谢！
![DeepDBB](https://github.com/user-attachments/assets/09f5aa1c-d41a-4757-ad3f-87d04925dbc4)
![DBB](https://github.com/user-attachments/assets/bdd642d4-f8ce-42f9-a16d-a0dd4f9d8f44)

**Comment by wandahangFY** [comment]
上传的代码确实和图片中的不一致，DeepDBB也没有正式公开论文，有需要的话，可以自行添加
 万达航
***@***.***
  签名由 网易灵犀办公 定制


Original:
From:Ma1229< ***@***.***>Date:2024-11-05 11:08:33To:wandahangFY/YOLO-MIF< ***@***.***>Cc:Subscribed< ***@***.***>Subject:[wandahangFY/YOLO-MIF] DeepDBB结构图与代码不对应？ (Issue #7)
你好！你们的工作对我启发很大！
 我在研究DeepDBB时，发现代码中所对应的第二条分支（后半段的K*K接BN）似乎并没有被替换为图中的LDBB，请问是我的理解错了吗，请指正，感谢！
 DeepDBB.png (view on web)
 DBB.png (view on web)

**Comment by wandahangFY** [comment]
改的时候记得注意padding对应起来
 万达航
***@***.***
  签名由 网易灵犀办公 定制


Original:
From:Ma1229< ***@***.***>Date:2024-11-05 11:08:33To:wandahangFY/YOLO-MIF< ***@***.***>Cc:Subscribed< ***@***.***>Subject:[wandahangFY/YOLO-MIF] DeepDBB结构图与代码不对应？ (Issue #7)
你好！你们的工作对我启发很大！
 我在研究DeepDBB时，发现代码中所对应的第二条分支（后半段的K*K接BN）似乎并没有被替换为图中的LDBB，请问是我的理解错了吗，请指正，感谢！
 DeepDBB.png (view on web)
 DBB.png (view on web)

**Comment by bolt958** [comment]
了解了，感谢！
